baseURL = "https://example.com"

[[module.imports]]
path = "github.com/Andywugh/encrypt"

[params.encrypt]
password = "hugomods.com"
storage = "session"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "gruvbox"
